#!/usr/bin/env bash
# ============================================================================
# build.sh — PaginasAudit Bundle Generator
# ============================================================================
# Generates a single self-contained executable `/usr/local/bin/paginas-audit`
# that embeds all libraries, modules, and Python scripts.
#
# Uso:
#   bash build.sh                    → genera ./paginas-audit
#   bash build.sh /path/to/output    → genera en ruta específica
#
# El output es un solo script bash que no depende de archivos externos.
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="${SCRIPT_DIR}/paginas-auditorias"
OUTPUT="${1:-${SCRIPT_DIR}/paginas-audit}"

# ---- Ordered file list (dependency order) ---------------------------------
# build.sh will cat these in order, stripping guards and source directives
FILES=(
    "lib/colors.sh"
    "lib/logging.sh"
    "lib/utils.sh"
    "lib/ui.sh"
    "lib/verify.sh"
    "config/tools.db"
    "modules/01-assessment.sh"
    "modules/02-malware.sh"
    "modules/03-brand-protection.sh"
    "modules/04-incident-response.sh"
    "modules/05-sast.sh"
    "modules/06-sca-sbom.sh"
    "modules/07-exploit-guides.sh"
    "modules/00-automated-audit.sh"
    "audit.sh"
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

info()  { echo "  [INFO] $*"; }
ok()    { echo "  [ OK ] $*"; }
warn()  { echo "  [WARN] $*"; }

# Guard pattern: [[ -n "${__XXX_LOADED:-}" ]] && return 0\nreadonly __XXX_LOADED=true
# (multiline, need to match across two lines)
strip_guard() {
    perl -0pe 's/^\[\[ -n "\$\{__\w+_LOADED:-}" \]\] \&\& return 0\nreadonly __\w+_LOADED=true\n//gm' "$1"
}

# Strip source directives and final main call for bundled files
strip_source() {
    # Remove source "${SCRIPT_DIR}/lib/xxx.sh"
    # Remove source "${SCRIPT_DIR}/config/tools.db"
    # Remove source "${SCRIPT_DIR}/modules/xxx.sh"
    # Remove source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/xxx.sh"
    #   (lib/ files use this pattern for internal dependencies)
    # Remove trailing main "$@" (bundle has its own at the end)
    grep -v '^source "${SCRIPT_DIR}/lib/' | \
    grep -v '^source "${SCRIPT_DIR}/config/tools.db"' | \
    grep -v '^source "${SCRIPT_DIR}/modules/' | \
    grep -v 'source.*BASH_SOURCE.*pwd)' | \
    grep -v '^main "\$@"$'
}

# Transform SCRIPT_DIR references to runtime paths
transform_paths() {
    sed \
        -e 's|"${SCRIPT_DIR}/config/settings.cfg"|"${__PAD_CONF_DIR}/settings.cfg"|g' \
        -e 's|"${SCRIPT_DIR}/logs"|"${__PAD_LOG_DIR}"|g' \
        -e 's|"${SCRIPT_DIR}/reports/installation-report"|"${__PAD_TMP_DIR}/installation-report"|g' \
        -e 's|"${SCRIPT_DIR}/reports/verification-report"|"${__PAD_TMP_DIR}/verification-report"|g' \
        -e 's|"${SCRIPT_DIR}/audits"|"${__PAD_AUDIT_DIR}"|g' \
        -e 's|"${SCRIPT_DIR}/lib/docx_report.py"|"${__PAD_DOCX_SCRIPT}"|g' \
        -e '/^if \[\[ -f "\${SCRIPT_DIR}\/README.md" \]\]; then/,/^fi$/d' \
        "$1"
}

# CRLF → LF (files may come from Windows)
fix_line_endings() {
    # stdin → stdout, convert Windows \r\n to Unix \n
    perl -pe 's/\r\n/\n/g'
}

# Strip auto-execute blocks at end of module files:
#   if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
#       ...
#   fi
# This prevents modules from running immediately when bundled.
# Matches both simple (single call) and complex (if-else-fi) blocks.
strip_autoexec() {
    perl -0pe 's/\n# ---- Auto-Execute.*?\nif \[\[ "\$\{BASH_SOURCE\[0\]\}" == "\$\{0\}" \]\]; then\n(?:.*?\n)*?fi\n//gs' "$1"
}

# Combine: normalize → strip auto-exec → strip guard → strip source → transform paths
process_file() {
    local file="$1"
    local tmp1 tmp2 tmp3 tmp4
    tmp1=$(mktemp)
    tmp2=$(mktemp)
    tmp3=$(mktemp)
    tmp4=$(mktemp)

    # First fix line endings, then strip auto-execute blocks, guards, sources, and transform paths
    fix_line_endings < "$file" > "$tmp1"
    strip_autoexec "$tmp1" > "$tmp2"
    strip_guard "$tmp2" > "$tmp3"
    strip_source < "$tmp3" > "$tmp4"
    transform_paths "$tmp4"

    rm -f "$tmp1" "$tmp2" "$tmp3" "$tmp4"
}

# ---------------------------------------------------------------------------
# Build bundle header
# ---------------------------------------------------------------------------

build_header() {
    cat << 'HEADER'
#!/usr/bin/env bash
# ============================================================================
# paginas-audit — PaginasAudit Cyber Audit Toolkit (self-contained)
# ============================================================================
# Generated by build.sh — do not edit directly.
# Source: https://github.com/DavidsmSilva/Auditorias-Paginas
# ============================================================================

set -euo pipefail
IFS=$'\n\t'

# ---- Runtime paths (no external files needed) ------------------------------
__PAD_CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/paginas-audit"
__PAD_DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/paginas-audit"
__PAD_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/paginas-audit"
__PAD_TMP_DIR="/tmp/paginas-audit.$$"
__PAD_LOG_DIR="${__PAD_DATA_DIR}/logs"
__PAD_AUDIT_DIR="${__PAD_DATA_DIR}/audits"
__PAD_DOCX_SCRIPT="${__PAD_TMP_DIR}/docx_report.py"

# Ensure runtime directories exist
mkdir -p "$__PAD_CONF_DIR" "$__PAD_DATA_DIR" "$__PAD_CACHE_DIR" "$__PAD_TMP_DIR"
mkdir -p "$__PAD_LOG_DIR" "$__PAD_AUDIT_DIR"

# Copy default settings.cfg if not present
if [[ ! -f "${__PAD_CONF_DIR}/settings.cfg" ]]; then
    cat > "${__PAD_CONF_DIR}/settings.cfg" << 'CONFEOF'
# ============================================================================
# settings.cfg — PaginasAudit User Configuration
# ============================================================================
LOG_LEVEL="INFO"
LOG_JSON=false
INSTALL_RETRIES=2
INSTALL_RETRY_DELAY=3
INSTALL_TIMEOUT=300
UPDATE_CHECK=true
UPDATE_CHANNEL="stable"
GENERATE_REPORT=true
REPORT_FORMAT="both"
OPEN_REPORT=false
AUTO_INSTALL_DEPS=true
SKIP_INSTALLED=true
SHOW_TOOL_DESCS=true
PARALLEL_INSTALL=false
MAX_PARALLEL_JOBS=3
APT_MIRROR=""
INSTALL_PREFIX=""
KEEP_DOWNLOADS=false
CACHE_DIR="/tmp/PaginasAudit-cache"
AUDITOR_NAME=""
CLIENT_NAME=""
ENGAGEMENT_ID=""
CONFEOF
    chmod 644 "${__PAD_CONF_DIR}/settings.cfg"
fi

# ---- Load settings ---------------------------------------------------------
SETTINGS_FILE="${__PAD_CONF_DIR}/settings.cfg"
if [[ -f "$SETTINGS_FILE" ]]; then
    source "$SETTINGS_FILE" 2>/dev/null || true
fi
export SKIP_INSTALLED AUTO_INSTALL_DEPS

HEADER
}

# ---------------------------------------------------------------------------
# Embed docx_report.py as base64
# ---------------------------------------------------------------------------

embed_docx_py() {
    local py_file="${SRC_DIR}/lib/docx_report.py"
    if [[ ! -f "$py_file" ]]; then
        warn "docx_report.py no encontrado — omitiendo"
        return
    fi

    local b64
    b64=$(base64 -w0 "$py_file" 2>/dev/null || base64 "$py_file" 2>/dev/null || cat "$py_file" | base64)
    echo ""
    echo "# ---- Embedded: docx_report.py (base64) ------------------------------"
    echo "__PAD_DOCX_B64='${b64}'"
    echo ""
    cat << 'PYDECODE'
# Decode docx_report.py on first run
if [[ ! -f "$__PAD_DOCX_SCRIPT" ]]; then
    echo "$__PAD_DOCX_B64" | base64 -d > "$__PAD_DOCX_SCRIPT" 2>/dev/null || \
    echo "$__PAD_DOCX_B64" | python3 -c "import sys; import base64; sys.stdout.buffer.write(base64.b64decode(sys.stdin.read()))" > "$__PAD_DOCX_SCRIPT" 2>/dev/null || true
    chmod +x "$__PAD_DOCX_SCRIPT" 2>/dev/null || true
fi

PYDECODE
}

# ---------------------------------------------------------------------------
# Build the bundle
# ---------------------------------------------------------------------------

build_bundle() {
    local output="$1"
    info "Generando bundle → ${output}"

    # Create a temp build file
    local build_tmp
    build_tmp=$(mktemp)

    # 1. Write header
    build_header > "$build_tmp"
    ok "Header escrito"

    # 2. Embed Python scripts
    embed_docx_py >> "$build_tmp"
    ok "docx_report.py embebido"

    # 3. Append each source file (transformed)
    local count=0 total=${#FILES[@]}
    for relpath in "${FILES[@]}"; do
        count=$((count + 1))
        local filepath="${SRC_DIR}/${relpath}"
        if [[ ! -f "$filepath" ]]; then
            warn "[${count}/${total}] ${relpath} — no encontrado, saltando"
            continue
        fi

        # Process the file: strip guard, strip source, transform paths
        {
            echo ""
            echo "# ==================================================================="
            echo "# Embedded: ${relpath}"
            echo "# ==================================================================="
            echo ""
            process_file "$filepath"
        } >> "$build_tmp"

        info "[${count}/${total}] ${relpath} — embehido"
    done

    # 4. Add cleanup trap
    cat >> "$build_tmp" << 'CLEANUP'

# ---- Cleanup temporary files on exit ---------------------------------------
__pad_cleanup() {
    rm -rf "$__PAD_TMP_DIR" 2>/dev/null || true
}
trap __pad_cleanup EXIT

# ---- Main entry ------------------------------------------------------------
main "$@"
CLEANUP

    # 5. Make executable and copy to output
    chmod +x "$build_tmp"
    cp "$build_tmp" "$output"
    rm -f "$build_tmp"

    ok "Bundle generado: ${output} ($(wc -c < "$output") bytes)"
    echo ""
    echo "  Para instalar globalmente:"
    echo "    sudo cp ${output} /usr/local/bin/paginas-audit"
    echo "    paginas-audit --help"
    echo ""
    echo "  O ejecutar directamente:"
    echo "    bash ${output} --audit https://ejemplo.com"
}

# ---- Main ------------------------------------------------------------------

main() {
    echo ""
    echo "  ╔═══════════════════════════════════════════════════╗"
    echo "  ║  PaginasAudit — Bundle Generator                 ║"
    echo "  ╚═══════════════════════════════════════════════════╝"
    echo ""

    # Verify source directory
    if [[ ! -d "$SRC_DIR" ]]; then
        echo "  [ERR ] Directorio fuente no encontrado: ${SRC_DIR}"
        echo "  Ejecute este script desde la raíz del repositorio."
        exit 1
    fi

    # Pre-check files
    local missing=0
    for relpath in "${FILES[@]}"; do
        if [[ ! -f "${SRC_DIR}/${relpath}" ]]; then
            warn "Falta: ${relpath}"
            missing=$((missing + 1))
        fi
    done
    if [[ $missing -gt 0 ]]; then
        echo "  [ERR ] ${missing} archivos faltantes. Abortando."
        exit 1
    fi
    ok "Todos los archivos fuente verificados"

    build_bundle "$OUTPUT"

    # Verify the bundle works
    echo ""
    info "Verificando bundle..."
    if head -1 "$OUTPUT" | grep -q "#!/usr/bin/env bash"; then
        ok "Shebang correcto"
    else
        warn "Shebang ausente"
    fi
    if grep -q "paginas-audit" "$OUTPUT"; then
        ok "Identificador presente"
    fi
    if grep -q '__PAD_DOCX_B64' "$OUTPUT" 2>/dev/null; then
        ok "Python scripts embebidos"
    fi
}

main "$@"
